name: linux

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  linux-workspace-automation:

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create workspace
        run: |
          ./flutter_workspace.py

      - name: Test workspace
        run: |
          source ./setup_env.sh
          flutter doctor -v
          dart --version
