name: macos

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    paths-ignore:
      - .github/workflows/windows.yaml
      - .github/workflows/ubuntu.yml
      - .github/workflows/ubuntu-legacy.yml
      - .github/workflows/fedora.yml
      - '**/*.md'
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:
  build-matrix:
    if: "!contains(github.event.pull_request.labels.*.name, 'ci: skip macos')"
    runs-on: ubuntu-latest
    outputs:
      llvm-versions: ${{ steps.assemble-matrix.outputs.llvm-versions }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Assemble build matrix
        id: assemble-matrix
        uses: ./.github/actions/build-matrix

  run:
    needs: build-matrix
    env:
      NONINTERACTIVE: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-15 ]
        llvm: ${{ fromJSON(needs.build-matrix.outputs.llvm-versions) }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check Environment
        run: |
          echo "Running on macOS version: $(sw_vers -productVersion)"
          echo "Running on architecture: $(uname -m)"
          echo "Current directory: $(pwd)"
          echo "Environment variables:"
          env
          
      - name: Brew fixup
        run: |
          brew upgrade |true
          brew cleanup |true
          brew doctor |true
          ruby -v
          
      - name: Create workspace
        shell: bash
        env:
          CI: true
          GITHUB_ACTIONS: true
        run: |
          env
          cd $GITHUB_WORKSPACE
          pwd; ls -la
          PREFER_LLVM=${{ matrix.llvm }} ./flutter_workspace.py
          cat ./setup_env.sh

      - name: Test workspace
        shell: bash
        env:
          CI: true
          GITHUB_ACTIONS: true
        run: |
          env
          cd $GITHUB_WORKSPACE
          pwd; ls -la
          . ./setup_env.sh
          dart --version
