name: ubuntu

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    paths-ignore:
      - .github/workflows/macos.yaml
      - .github/workflows/windows.yaml
      - .github/workflows/ubuntu-legacy.yml
      - .github/workflows/fedora.yml
      - '**/*.md'
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:
  build-matrix:
    if: "!contains(github.event.pull_request.labels.*.name, 'ci: skip ubuntu')"
    runs-on: ubuntu-latest
    outputs:
      llvm-versions: ${{ steps.assemble-matrix.outputs.llvm-versions }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Assemble build matrix
        id: assemble-matrix
        uses: ./.github/actions/build-matrix

  run:
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm]
        llvm: ${{ fromJSON(needs.build-matrix.outputs.llvm-versions) }}
        exclude:
          # LLVM < 16 not supported for >= Ubuntu 24.04
          - os: ubuntu-24.04
            llvm: 14
          - os: ubuntu-24.04-arm
            llvm: 14
          - os: ubuntu-24.04
            llvm: 15
          - os: ubuntu-24.04-arm
            llvm: 15

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check Environment
        id: check_environment
        shell: bash
        run: |
          echo "Running on Ubuntu version: $(lsb_release -d | cut -f2)"
          echo "Running on architecture: $(uname -m)"
          echo "Current directory: $(pwd)"
          echo "Environment variables:"
          env

          # Get username
          echo "user=$(whoami)" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4

      - name: Create workspace
        uses: ./.github/actions/setup-workspace
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          cache: true
          cache-key: ${{ matrix.os }}-llvm${{ matrix.llvm }}
          user: ${{ steps.check_environment.outputs.user }}

      - name: Test workspace
        shell: bash
        env:
          CI: true
          GITHUB_ACTIONS: true
        run: |
          pwd; ls -la
          source ./setup_env.sh
          ls -la $FLUTTER_WORKSPACE
          dart --version

      - name: Test AOT
        if: ${{ !contains(matrix.os, 'arm') }}
        shell: bash
        env:
          CI: true
          GITHUB_ACTIONS: true
        run: |
          cd $GITHUB_WORKSPACE
          pwd; ls -la
          source ./setup_env.sh
          ./flutter_workspace.py --create-aot --app-path=./app/tcna-packages/packages/flatpak/example/
