name: windows-workspace-automation

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  workspace-automation:

    env:
      NONINTERACTIVE: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    strategy:
      matrix:
        os: [ windows-11-arm ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create workspace
        run: |
          python3.exe -m pip install --upgrade pip
          python3.exe -m pip install virtualenv
          ./flutter_workspace.ps1

      - name: Test workspace
        run: |
          ls
          ./setup_env.ps1
          flutter doctor -v
          dart --version
