name: ubuntu-workspace-automation

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  workspace-automation:

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        # macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-22.04, ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup workspace
        run: |
          sudo ./flutter_workspace.py

      - name: Source Environment
        shell: bash
        working-directory: workspace
        run: |
          source ./setup_env.sh
          flutter doctor -v
          dart --version
